### PR TITLE
Add documentation on dimensions of board

### LINKED ISSUE #17: [Feature Request] Export mechanical drawing of CyphalPicoBase/CAN

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
I added a pdf file with mechanical dimensions.
Which data do you need?

**Comment by aentinger** [comment]
It would be desirable if there was only the board visible within the PDF. Bonus points if you can show distance from edge of board to pin 1 of connector.

**Comment by generationmake** [comment]
@aentinger  here you go.

**Comment by aentinger** [comment]
Looking good :+1: Now if it could be made so that no number is crossed out by some other dimension line, then I shall  be most happy :grin:

**Comment by aentinger** [comment]
Ping @generationmake ☕ 👋

**Pull request merged**
