### PR TITLE
development for prototype release

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
@wuehr1999
any comments?

**Comment by wuehr1999** [comment]
Hi @generationmake 
I checked the schematics and could not find any errors. Great work ;-)
What about adding an additional WR-TBL691322310003 for can connection?

**Comment by aentinger** [comment]
Needs connectors for NeoPixels =)

**Comment by generationmake** [comment]
Hi 
@wuehr1999  There are now screw terminals for CAN
@aentinger Neopixels can be connected to CN12.

any more comments?

**Comment by aentinger** [comment]
Can the Raspberry Pi Pico be soldered directly to the board without headers (to minimise overall board height)?
And look at I found [here](https://www.reichelt.at/at/de/can-controller-mit-spi-schnittstelle-2-7--5-5-v-so-18-mcp-2515-i-so-p54515.html), does this one fit for your board? Shall I order a couple?

**Comment by generationmake** [comment]
Good Morning @aentinger 
You should be able to directly mount the Raspberry Pi Pico without headers if you don't use any THT parts (MCP2515 and crystal)
The MCP2515 from Reichelt would be fine but I will order it by myself because I need some more parts.
Thanks

**Comment by aentinger** [comment]
Given the find of the MCP2515 I'd would then be important to also get the SMD crystal :wink: .

Shall I also order some MCP2515 just for safe-keeping? (Crazy world we are living in...)

**Comment by generationmake** [comment]
board test successful. will merge.

**Pull request merged**
