### PR TITLE
correct cut out for serial connector

### LINKED ISSUE #25: [Feature Request] Increase size of outlet for Serial connector
Report by customer:

>Serial port hole is too narrow, connector won't fit through, I had to take the board pit, click it in, then put it back in.

image

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger 
please check. Thanks!
cut out was widened by a total of 1.5 mm

**Comment by aentinger** [comment]
It's in the oven :grin:

**Comment by aentinger** [comment]
Printed, looking good 👍 

IMG_20231121_122704_331

**Review by aentinger — APPROVED** [review]
Printing and size-check shows all good :+1:

**Pull request merged**
