### PR TITLE
Enclosure

### PR DESCRIPTION
**Pull request by generationmake**
add enclosure for pcb

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
Could you please print the enclosure and test it?
Thanks!

**Comment by aentinger** [comment]
Will do start of this week 👍

**Comment by aentinger** [comment]
I've printed the case, here are a couple of pictures:

IMG_20230124_091400_787
IMG_20230124_091346_347
IMG_20230124_091246_130
IMG_20230124_091238_925
IMG_20230124_091233_130
IMG_20230124_091225_219
IMG_20230124_091157_269
IMG_20230124_091147_704

**Review by aentinger — CHANGES_REQUESTED** [review]
* A wider opening for the USB. Currently you can't plug in the connector.
* A wider opening for the reset pin.

**Comment by generationmake** [comment]
@aentinger 
I increased the cut put for the USB connector.
The hole for the reset button is intentional. Under normal conditions this button shouldn't have to be pressed.
Could you please try it again? Thanks

**Comment by aentinger** [comment]
I've reprinted the bottom. While now in theory the plug could be inserted deeper in reality it seems that the full depth had already been reached ...

IMG_20230126_135425_461
IMG_20230126_135415_434

**Comment by generationmake** [comment]
enclosure was now successfully tested.
will merge

**Review by generationmake — COMMENTED** [review]
changed

**Pull request merged**
