### PR TITLE
Dev 0.3

### LINKED ISSUE #7: add protection to CAN
Add some ESD protection to CAN bus.
For example with PESD2CAN on data lines.
https://assets.nexperia.com/documents/data-sheet/PESD2CAN.pdf
and TVS diode on bus voltage.

### LINKED ISSUE #11: add qwiic logo
for i2c connector, see here: https://www.sparkfun.com/qwiic#faqs

### LINKED ISSUE #12: transform CN6, CN8 and CN11 into one single connector
to easier allow add-on boards

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: 

Can you please render a new schematic for me to review your changes?

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: 

Cyphal/CAN communication works, I'll give you a unit to verify all other functionality.

**Comment by generationmake** [comment]
First test was successful. will merge.

**Pull request merged**
