### PR TITLE
updated enclosure at serial and neopixel connector

### LINKED ISSUE #22: Feature Request: add cut-out for neopixel connector
Report by a customer:

I printed the CyphalPicoBase/CAN enclosure (using the file from GitHub) and the cover won't close, as the Neopixel connector is too tall for the cover spacers. You need to make a cut for the connector, I guess.

IMG_20231118_085319_661

### LINKED ISSUE #23: Feature Request: trim spacer on side of serial connector
Report by customer:

also, the cover spacer on the side of the serial connector is way too wide, so it's basically conflicting for space with the serial connector - would be good to trim the side of the spacer adjacent to the connector.

IMG_20231118_085411_683

### PR DESCRIPTION
**Pull request by generationmake**
fix collisions at serial and neopixel connector

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger 
could you please do a test print

**Comment by aentinger** [comment]
Its in the oven 🍰

**Comment by aentinger** [comment]
Good for serial port, still needs to be a bit wider for the NeoPixel connector.

IMG_20231118_161657_867
IMG_20231118_161709_145
IMG_20231118_161746_153

**Comment by generationmake** [comment]
Hi @aentinger 
It seems like I missed it only by 0.2 mm. So i slightly increased the cut out.
Additionally I updated the PCB with 3D data of the connectors.
Please try again. Thanks

**Comment by aentinger** [comment]
It's in the oven :cake:

**Comment by aentinger** [comment]
NeoPixel connector is good, but we need to consider a similar cut-out for the electrolyte capacitor.

IMG_20231119_113711_809

**Comment by generationmake** [comment]
Ok, thanks for the hint. I will add an additional cut out for the capacitor.
Did you check the cables (neopixels and qwiic)? Is it possible to connect? I think they should be easier because they don't have a latch.
Thanks.

**Comment by aentinger** [comment]
>Did you check the cables (neopixels and qwiic)? Is it possible to connect?

I don't have such cables available, but from what I can see they should be easy to connect.

**Comment by aentinger** [comment]
It's in the oven :+1:

**Comment by aentinger** [comment]
Its a perfect fit now ;)

IMG_20231120_065626_666

**Review by aentinger — APPROVED** [review]
Lgtm 👍

**Comment by generationmake** [comment]
finally ;-)
Let me update the main rendering and then I will merge.

**Pull request merged**
