### PR TITLE
Dev 0.2

### LINKED ISSUE #2: add possibility to supply servo from uavcan bus powe
possibility to bypass diode or similar.
but bigger servos may need external power

### LINKED ISSUE #3: switch to SMD parts
switch to SMD parts for MCP2515 and crystal.
also switch to direct mounting of Raspberry Pi Pico. take care of the USB connector and place it on the edge of the board.

### PR DESCRIPTION
**Pull request by generationmake**
development of next hardware revision to fix issues of the previous one.

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger , @wuehr1999
are there any comments from your side?

**Comment by aentinger** [comment]
Looks good to me. What I'd add are a couple of tantal capacitors to bolster the power supply in case of current surces (I'm looking at the two servo outputs esspecially, since all power supply is going via the CAN diode (in case of supplying via CAN which is the most likely usecase imho because no one wants a wiring disaster over the whole robot)).

**Comment by wuehr1999** [comment]
Hi @generationmake
I opened the project in KiCAD and found nothing critical. So everything looks good to me :+1:

**Comment by pavel-kirienko** [comment]
image

**Comment by generationmake** [comment]
The new revision was assembled and basic functions tested.
Everything is fine.
Will merge.

**Pull request merged**
